/**
 * This is a kingdee cosmic template project that is automatically generated by the Kingdee cosmic development assistant plugin. 
 * If there are any issues during the use process, you can provide feedback to the kingdee developer community website.
 * Website: https://developer.kingdee.com/developer?productLineId=29
 * Author: liebin.zheng
 * Generate Date: 2024-05-20 15:47:39
 */
package myg6.lib.app.common;

/**
 * lib云app应用-通用常量类<br>
 * 代码中不能存在硬编码敏感信息，如账号、密码、http外链、ftp外链、邮箱等。<br>
 * 标识或缓存的常量，需以"KEY_"、"FID_"、"ENTRY_"或"SUBENTRY_"作为变量的前缀。<br>
 *
 * @author myg6
 * @date 2024-05-20 15:47:39
 */
public class AppflgConstant {
	
	public static final String KEY_APP_NAME = "lib-app";

}
