/**
 * This is a kingdee cosmic template project that is automatically generated by the Kingdee cosmic development assistant plugin.
 * If there are any issues during the use process, you can provide feedback to the kingdee developer community website.
 * Website: https://developer.kingdee.com/developer?productLineId=29
 * Author: liebin.zheng
 * Generate Date: 2024-05-20 15:47:39
 */
package myg6.cosmic.debug;

import kd.cosmic.debug.tools.CosmicLauncher;

/**
 * 启动本地应用程序(微服务节点)
 */

public class DebugApplication {

    public static final String MY_IP = "10.21.204.111";

    //这里是redis在本地的地址

    private static final String REDIS_IP = "127.0.0.1:6379";

    public static void main(String[] args) {

//    	Thread.currentThread().setContextClassLoader(new KDSecurityClassLoader(Thread.currentThread().getContextClassLoader()));

        CosmicLauncher cosmic = new CosmicLauncher(false);

        cosmic.setClusterNumber("cosmic");

        cosmic.setTenantNumber("ierp");

        cosmic.setConfigUrl(MY_IP + ":2181?user=zookeeper&password=zookeeper");

        cosmic.setMcServerUrl("http://" + MY_IP + ":8090/");

        cosmic.setWebResPath("E:/ruanjianbei/static-file-service");

        cosmic.setFsServerUrl(MY_IP, 8100);

        cosmic.setImageServerUrl(MY_IP, 8100);

        cosmic.setMqConsumerRegister(true, "testlxler");
        //自定义本地苍穹调试服务的端口
        cosmic.setCosmicWepPort(8881);
//        cosmic.setDubboConfig(false, true, true);
        //开启轻分析
        //打开redis设置
        cosmic.setRedisConfig(REDIS_IP);

        cosmic.start();
    }
}