/**
 * This is a kingdee cosmic template project that is automatically generated by the Kingdee cosmic development assistant plugin.
 * If there are any issues during the use process, you can provide feedback to the kingdee developer community website.
 * Website: https://developer.kingdee.com/developer?productLineId=29
 * Author: liebin.zheng
 * Generate Date: 2024-05-20 15:47:39
 */
package myg6.cosmic.debug;

import kd.cosmic.debug.tools.CosmicLauncher;

/**
 * 启动本地应用程序(微服务节点)
 */
public class DebugApplication {
    public static void main(String[] args) {

//    	Thread.currentThread().setContextClassLoader(new KDSecurityClassLoader(Thread.currentThread().getContextClassLoader()));

        CosmicLauncher cosmic = new CosmicLauncher(false);

        cosmic.setClusterNumber("cosmic");

        cosmic.setTenantNumber("ierp");

        cosmic.setConfigUrl("10.21.207.149:2181?user=zookeeper&password=zookeeper");

        cosmic.setMcServerUrl("http://10.21.207.149:8090/");

        cosmic.setWebResPath("E:/ruanjianbei/static-file-service");

        cosmic.setFsServerUrl("10.21.207.149", 8100);

        cosmic.setImageServerUrl("10.21.207.149", 8100);

        cosmic.setMqConsumerRegister(true, "testlxler");
        //自定义本地苍穹调试服务的端口
        cosmic.setCosmicWepPort(8881);
//        cosmic.setDubboConfig(false, true, true);
        //开启轻分析
        cosmic.start();
    }
}